# coding: utf-8

# flake8: noqa

"""
    Food Delivery System

    A RESTful API for managing restaurants and food orders.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "AuthenticationApi",
    "HealthApi",
    "OrdersApi",
    "RestaurantsApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "HTTPValidationError",
    "LocationInner",
    "OrderCreate",
    "OrderOut",
    "RestaurantCreate",
    "RestaurantOut",
    "Token",
    "UserCreate",
    "UserLogin",
    "UserOut",
    "ValidationError",
]

# import apis into sdk package
from openapi_client.api.authentication_api import AuthenticationApi as AuthenticationApi
from openapi_client.api.health_api import HealthApi as HealthApi
from openapi_client.api.orders_api import OrdersApi as OrdersApi
from openapi_client.api.restaurants_api import RestaurantsApi as RestaurantsApi

# import ApiClient
from openapi_client.api_response import ApiResponse as ApiResponse
from openapi_client.api_client import ApiClient as ApiClient
from openapi_client.configuration import Configuration as Configuration
from openapi_client.exceptions import OpenApiException as OpenApiException
from openapi_client.exceptions import ApiTypeError as ApiTypeError
from openapi_client.exceptions import ApiValueError as ApiValueError
from openapi_client.exceptions import ApiKeyError as ApiKeyError
from openapi_client.exceptions import ApiAttributeError as ApiAttributeError
from openapi_client.exceptions import ApiException as ApiException

# import models into sdk package
from openapi_client.models.http_validation_error import HTTPValidationError as HTTPValidationError
from openapi_client.models.location_inner import LocationInner as LocationInner
from openapi_client.models.order_create import OrderCreate as OrderCreate
from openapi_client.models.order_out import OrderOut as OrderOut
from openapi_client.models.restaurant_create import RestaurantCreate as RestaurantCreate
from openapi_client.models.restaurant_out import RestaurantOut as RestaurantOut
from openapi_client.models.token import Token as Token
from openapi_client.models.user_create import UserCreate as UserCreate
from openapi_client.models.user_login import UserLogin as UserLogin
from openapi_client.models.user_out import UserOut as UserOut
from openapi_client.models.validation_error import ValidationError as ValidationError

