# coding: utf-8

"""
    Food Delivery System

    A RESTful API for managing restaurants and food orders.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.restaurant_out import RestaurantOut
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class OrderOut(BaseModel):
    """
    OrderOut
    """ # noqa: E501
    id: StrictInt
    restaurant_id: StrictInt
    user_id: StrictInt
    user_name: StrictStr
    status: StrictStr
    created_at: datetime
    restaurant: Optional[RestaurantOut] = None
    __properties: ClassVar[List[str]] = ["id", "restaurant_id", "user_id", "user_name", "status", "created_at", "restaurant"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OrderOut from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of restaurant
        if self.restaurant:
            _dict['restaurant'] = self.restaurant.to_dict()
        # set to None if restaurant (nullable) is None
        # and model_fields_set contains the field
        if self.restaurant is None and "restaurant" in self.model_fields_set:
            _dict['restaurant'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OrderOut from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "restaurant_id": obj.get("restaurant_id"),
            "user_id": obj.get("user_id"),
            "user_name": obj.get("user_name"),
            "status": obj.get("status"),
            "created_at": obj.get("created_at"),
            "restaurant": RestaurantOut.from_dict(obj["restaurant"]) if obj.get("restaurant") is not None else None
        })
        return _obj


