# coding: utf-8

"""
    Food Delivery System

    A RESTful API for managing restaurants and food orders.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.authentication_api import AuthenticationApi


class TestAuthenticationApi(unittest.TestCase):
    """AuthenticationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthenticationApi()

    def tearDown(self) -> None:
        pass

    def test_login_auth_login_post(self) -> None:
        """Test case for login_auth_login_post

        Login
        """
        pass

    def test_signup_auth_signup_post(self) -> None:
        """Test case for signup_auth_signup_post

        Signup
        """
        pass


if __name__ == '__main__':
    unittest.main()
