# coding: utf-8

"""
    Food Delivery System

    A RESTful API for managing restaurants and food orders.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.restaurants_api import RestaurantsApi


class TestRestaurantsApi(unittest.TestCase):
    """RestaurantsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RestaurantsApi()

    def tearDown(self) -> None:
        pass

    def test_create_restaurant_restaurants_post(self) -> None:
        """Test case for create_restaurant_restaurants_post

        Create Restaurant
        """
        pass

    def test_get_restaurant_restaurants_restaurant_id_get(self) -> None:
        """Test case for get_restaurant_restaurants_restaurant_id_get

        Get Restaurant
        """
        pass

    def test_list_restaurants_restaurants_get(self) -> None:
        """Test case for list_restaurants_restaurants_get

        List Restaurants
        """
        pass


if __name__ == '__main__':
    unittest.main()
