# coding: utf-8

"""
    Food Delivery System

    A RESTful API for managing restaurants and food orders.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.restaurant_create import RestaurantCreate

class TestRestaurantCreate(unittest.TestCase):
    """RestaurantCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RestaurantCreate:
        """Test RestaurantCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RestaurantCreate`
        """
        model = RestaurantCreate()
        if include_optional:
            return RestaurantCreate(
                name = '',
                is_open = True
            )
        else:
            return RestaurantCreate(
                name = '',
        )
        """

    def testRestaurantCreate(self):
        """Test RestaurantCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
