# coding: utf-8

"""
    Food Delivery System

    A RESTful API for managing restaurants and food orders.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.orders_api import OrdersApi


class TestOrdersApi(unittest.TestCase):
    """OrdersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OrdersApi()

    def tearDown(self) -> None:
        pass

    def test_cancel_order_orders_order_id_delete(self) -> None:
        """Test case for cancel_order_orders_order_id_delete

        Cancel Order
        """
        pass

    def test_list_my_orders_orders_get(self) -> None:
        """Test case for list_my_orders_orders_get

        List My Orders
        """
        pass

    def test_place_order_orders_post(self) -> None:
        """Test case for place_order_orders_post

        Place Order
        """
        pass


if __name__ == '__main__':
    unittest.main()
