# coding: utf-8

"""
    Food Delivery System

    A RESTful API for managing restaurants and food orders.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.restaurant_out import RestaurantOut

class TestRestaurantOut(unittest.TestCase):
    """RestaurantOut unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RestaurantOut:
        """Test RestaurantOut
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RestaurantOut`
        """
        model = RestaurantOut()
        if include_optional:
            return RestaurantOut(
                id = 56,
                name = '',
                is_open = True
            )
        else:
            return RestaurantOut(
                id = 56,
                name = '',
                is_open = True,
        )
        """

    def testRestaurantOut(self):
        """Test RestaurantOut"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
